name: Autobuild for Docker

on: [push, workflow_dispatch, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | buildah login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin "${{ secrets.DOCKER_HOST }}"
      - name: Enable multi-arch
        run: |
          sudo podman run --rm --privileged docker.io/tonistiigi/binfmt --install all
      - name: Build the image
        run: |
          buildah bud --squash --format=docker \
            --tag "${{ secrets.DOCKER_TAG }}:7.0" \
            --tag "${{ secrets.DOCKER_TAG }}:latest" \
            --manifest mongodb \
            --platform linux/arm64 \
            --platform linux/amd64 \
            .
      - name: Push the image
        run: |
          buildah manifest push --all mongodb docker://docker.io/${{ secrets.DOCKER_TAG }}
